-- 0022_npc_population.sql — a cidade ganha população (PRD §25).
--
-- GERADO por packages/npc/scripts/gen-population.mjs; não edite à mão — mude
-- o gerador e gere de novo (as posições são validadas contra a planta de
-- cada cena lá).
--
-- Três classes de personagem, e a classe é COLUNA (`kind`), não convenção:
--
--   cognitive  guiado por modelo de linguagem, persona versionada, memória,
--              reflexão com auditor (o Nilo; agora também a Dalva).
--   social     vontade dentro de uma caixa: personalidade em cinco números,
--              humor, necessidades e RELAÇÕES (tabela nova abaixo) — parece
--              querer, e quer, mas só o que o código enumera. Zero LLM.
--   ambient    máquina de estados sobre um programa (ficar, andar, sentar,
--              dançar); quando muito uma fala de balcão. Sem vontade.
--
-- `profile` guarda o que cada classe precisa: programa (ambient) ou
-- personalidade + cantos + frases (social). Para os cognitivos fica vazio: o
-- que eles são está em `npc_persona_versions`.
ALTER TABLE streampolis.npc_agents
  ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'cognitive'
    CHECK (kind IN ('cognitive', 'social', 'ambient')),
  ADD COLUMN IF NOT EXISTS profile JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Relações de um personagem social com jogadores e com outros personagens.
-- Uma linha por par; `affinity` é o número, `stage` é a leitura dele
-- (gravada para o painel filtrar sem reimplementar os cortes). Não é FK para
-- `users`: a relação com alguém que apagou a conta fica, sem nome novo.
CREATE TABLE IF NOT EXISTS streampolis.npc_relations (
  npc_id       UUID NOT NULL REFERENCES streampolis.npc_agents(id) ON DELETE CASCADE,
  other_id     UUID NOT NULL,
  other_kind   TEXT NOT NULL CHECK (other_kind IN ('player', 'npc')),
  other_name   TEXT NOT NULL,
  affinity     REAL NOT NULL DEFAULT 0,
  stage        TEXT NOT NULL DEFAULT 'stranger' CHECK (stage IN ('grudge', 'stranger', 'known', 'friend', 'close')),
  encounters   INTEGER NOT NULL DEFAULT 1,
  exchanges    INTEGER NOT NULL DEFAULT 0,
  facts        TEXT[] NOT NULL DEFAULT '{}',
  first_seen   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_greeted TIMESTAMPTZ,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (npc_id, other_id)
);
CREATE INDEX IF NOT EXISTS npc_relations_por_pessoa ON streampolis.npc_relations (other_id, affinity DESC);

-- Freios por classe (SPECs §64), além do geral `npc_enabled`: se sessenta
-- corpos pesarem no servidor, desliga-se a classe, não a cidade.
INSERT INTO streampolis.feature_flags (key, enabled, description) VALUES
  ('npc_ambient_enabled', TRUE, 'Personagens de ambiente (figurantes com corpo de verdade).'),
  ('npc_social_enabled', TRUE, 'Personagens sociais (vontade em caixa, relações, sem LLM).')
ON CONFLICT (key) DO UPDATE SET description = EXCLUDED.description;

UPDATE streampolis.npc_agents SET kind = 'cognitive' WHERE slug = 'nilo';


-- ---------------------------------------------------------------- elenco --
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a101', 'marcos', 'Marcos', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"m_worker_head","hairColor":5,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":1.06,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":23.1,"z":-21.5},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a102', 'renata', 'Renata', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"f_punk_head","hairColor":8,"top":"f_punk_top","bottom":"f_punk_bottom","shoes":"f_punk_shoes","accessory":"","height":1.05,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":20,"z":24.6},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a103', 'tiago', 'Tiago', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"m_casual_character_head","hairColor":2,"top":"m_casual_character_top","bottom":"m_casual_character_bottom","shoes":"m_casual_character_shoes","accessory":"","height":0.96,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":-11.2,"z":3.8},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a104', 'paula', 'Paula', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"f_adventurer_head","hairColor":3,"top":"f_adventurer_top","bottom":"f_adventurer_bottom","shoes":"f_adventurer_shoes","accessory":"","height":0.94,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":29.2,"z":4.6},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a105', 'edu', 'Edu', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"m_casual_character_head","hairColor":9,"top":"m_casual_character_top","bottom":"m_casual_character_bottom","shoes":"m_casual_character_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":0,"z":12},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a106', 'cintia', 'Cíntia', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"f_punk_head","hairColor":6,"top":"f_punk_top","bottom":"f_punk_bottom","shoes":"f_punk_shoes","accessory":"","height":1,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":-12,"z":0},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a107', 'wagner', 'Wagner', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"m_hoodie_character_head","hairColor":0,"top":"m_hoodie_character_top","bottom":"m_hoodie_character_bottom","shoes":"m_hoodie_character_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":0,"z":-12},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a108', 'larissa', 'Larissa', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"f_animated_woman_head","hairColor":7,"top":"f_animated_woman_top","bottom":"f_animated_woman_bottom","shoes":"f_animated_woman_shoes","accessory":"","height":1.03,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"passante","program":[{"do":"walk","secs":[3,9]},{"do":"walk","secs":[2,6]},{"do":"stand","at":{"x":-24.6,"z":18.5},"secs":[12,35]},{"do":"walk","secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a109', 'seu-antenor', 'Seu Antenor', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_punk_head","hairColor":8,"top":"m_punk_top","bottom":"m_punk_bottom","shoes":"m_punk_shoes","accessory":"","height":1.03,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"sentado no banco","program":[{"do":"sit","near":{"x":6.96,"z":13.51},"secs":[150,320]},{"do":"walk","secs":[4,8]},{"do":"sit","near":{"x":-11.6,"z":-9.82},"secs":[120,260]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a10a', 'dona-lurdes', 'Dona Lurdes', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"f_animated_woman_head","hairColor":1,"top":"f_animated_woman_top","bottom":"f_animated_woman_bottom","shoes":"f_animated_woman_shoes","accessory":"","height":1.02,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"sentado no banco","program":[{"do":"sit","near":{"x":-9.82,"z":11.6},"secs":[150,320]},{"do":"walk","secs":[4,8]},{"do":"sit","near":{"x":4.64,"z":-14.48},"secs":[120,260]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a10b', 'pedrinho', 'Pedrinho', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"m_business_man_head","hairColor":7,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":0.98,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"sentado no banco","program":[{"do":"sit","near":{"x":11.7,"z":28.17},"secs":[150,320]},{"do":"walk","secs":[4,8]},{"do":"sit","near":{"x":-30.24,"z":-3.95},"secs":[120,260]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a10c', 'vanda', 'Vanda', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"f_adventurer_head","hairColor":2,"top":"f_adventurer_top","bottom":"f_adventurer_bottom","shoes":"f_adventurer_shoes","accessory":"","height":1,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"sentado no banco","program":[{"do":"sit","near":{"x":-28.17,"z":11.7},"secs":[150,320]},{"do":"walk","secs":[4,8]},{"do":"sit","near":{"x":3.95,"z":-30.24},"secs":[120,260]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a10d', 'gustavo', 'Gustavo', '{"bodyPreset":0,"skinTone":3,"facePreset":0,"hair":"m_worker_head","hairColor":2,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"olhando o telão","program":[{"do":"stand","at":{"x":-3.5,"z":-25},"yaw":2.771,"secs":[90,240]},{"do":"walk","secs":[5,12]},{"do":"stand","at":{"x":-3.5,"z":-25},"yaw":2.771,"secs":[60,180]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a10e', 'aline', 'Aline', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"f_worker_head","hairColor":7,"top":"f_worker_top","bottom":"f_worker_bottom","shoes":"f_worker_shoes","accessory":"","height":1.01,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"olhando o telão","program":[{"do":"stand","at":{"x":0.5,"z":-23.8},"yaw":-3.093,"secs":[90,240]},{"do":"walk","secs":[5,12]},{"do":"stand","at":{"x":0.5,"z":-23.8},"yaw":-3.093,"secs":[60,180]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a10f', 'fabio', 'Fábio', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"m_business_man_head","hairColor":2,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":0.95,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"olhando o telão","program":[{"do":"stand","at":{"x":4,"z":-25.5},"yaw":-2.702,"secs":[90,240]},{"do":"walk","secs":[5,12]},{"do":"stand","at":{"x":4,"z":-25.5},"yaw":-2.702,"secs":[60,180]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a110', 'beto', 'Beto', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"m_worker_head","hairColor":4,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":0.98,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"conversando no quiosque leste","program":[{"do":"stand","at":{"x":16.47,"z":16.69},"yaw":2.214,"secs":[70,160]},{"do":"stand","at":{"x":16.47,"z":16.69},"yaw":2.214,"pose":"wave","secs":[3,4]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a111', 'carla', 'Carla', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"f_suit_head","hairColor":7,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":0.96,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"conversando no quiosque leste","program":[{"do":"stand","at":{"x":18.07,"z":15.49},"yaw":-0.927,"secs":[90,200]},{"do":"stand","at":{"x":18.07,"z":15.49},"yaw":-0.927,"pose":"clap","secs":[3,4]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a112', 'henrique', 'Henrique', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_casual_character_head","hairColor":6,"top":"m_casual_character_top","bottom":"m_casual_character_bottom","shoes":"m_casual_character_shoes","accessory":"","height":1.01,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"conversando no quiosque oeste","program":[{"do":"stand","at":{"x":-17.93,"z":-17.24},"yaw":2.29,"secs":[70,160]},{"do":"stand","at":{"x":-17.93,"z":-17.24},"yaw":2.29,"pose":"wave","secs":[3,4]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a113', 'simone', 'Simone', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"f_adventurer_head","hairColor":4,"top":"f_adventurer_top","bottom":"f_adventurer_bottom","shoes":"f_adventurer_shoes","accessory":"","height":0.99,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"conversando no quiosque oeste","program":[{"do":"stand","at":{"x":-16.33,"z":-18.64},"yaw":-0.852,"secs":[90,200]},{"do":"stand","at":{"x":-16.33,"z":-18.64},"yaw":-0.852,"pose":"clap","secs":[3,4]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a114', 'seu-nelson', 'Seu Nelson', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"m_worker_head","hairColor":6,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":0.97,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"quiosqueiro","program":[{"do":"stand","at":{"x":-17.57,"z":17.79},"yaw":2.362,"secs":[200,400]},{"do":"walk","to":{"x":-16.23,"z":16.44},"secs":[6,12]}],"lines":["Fechado hoje, como todo dia. Mas pode ficar por aqui.","Não vendo nada, não — só faço companhia ao quiosque.","Se procura o Nilo, ele anda pela praça toda. Sempre acha."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a115', 'joana', 'Joana', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"f_animated_woman_niitlv9nxs_head","hairColor":0,"top":"f_animated_woman_niitlv9nxs_top","bottom":"f_animated_woman_niitlv9nxs_bottom","shoes":"f_animated_woman_niitlv9nxs_shoes","accessory":"","height":0.97,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"olhando o monumento","program":[{"do":"stand","at":{"x":5.91,"z":7.44},"yaw":-2.47,"secs":[50,140]},{"do":"walk","to":{"x":-9.4,"z":1.34},"secs":[40,120]},{"do":"walk","secs":[6,14]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a116', 'ivo', 'Ivo', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_beach_character_head","hairColor":4,"top":"m_beach_character_top","bottom":"m_beach_character_bottom","shoes":"m_beach_character_shoes","accessory":"","height":0.98,"body":"v1"}'::jsonb, 'central_plaza', 'ambient', '{"role":"olhando o monumento","program":[{"do":"stand","at":{"x":-6.9,"z":-6.53},"yaw":0.813,"secs":[50,140]},{"do":"walk","to":{"x":9.12,"z":-2.65},"secs":[40,120]},{"do":"walk","secs":[6,14]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b201', 'bia', 'Bia', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"f_animated_woman_head","hairColor":2,"top":"f_animated_woman_top","bottom":"f_animated_woman_bottom","shoes":"f_animated_woman_shoes","accessory":"","height":0.98,"body":"v1"}'::jsonb, 'central_plaza', 'social', '{"archetype":"tagarela","personality":{"sociable":0.95,"curious":0.7,"cheerful":0.85,"patient":0.6,"loyal":0.6},"haunts":[{"x":16.46,"z":15.34},{"x":6,"z":6}],"intro":"Sou a Bia, personagem daqui da praça — a que fala pelos cotovelos.","topics":["Já reparou que o telão passa o mesmo vídeo o dia inteiro? Eu já decorei.","O Nilo diz que chegou antes de todo mundo. Eu acho que ele inventa.","A melhor hora da praça é quando junta gente nos quiosques.","Tem gente que atravessa a praça correndo. Correndo pra onde?"],"quirk":"Enfim — o que eu tava dizendo mesmo?"}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b202', 'teo', 'Teo', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_hoodie_character_head","hairColor":2,"top":"m_hoodie_character_top","bottom":"m_hoodie_character_bottom","shoes":"m_hoodie_character_shoes","accessory":"","height":1.01,"body":"v1"}'::jsonb, 'central_plaza', 'social', '{"archetype":"timido","personality":{"sociable":0.25,"curious":0.6,"cheerful":0.5,"patient":0.85,"loyal":0.9},"haunts":[{"x":-17.97,"z":24.76},{"x":-11.85,"z":-27.38}],"intro":"Teo. Sou personagem da praça. Fico mais pelos bancos de fora.","topics":["Gosto do banco de fora. Dá pra ver tudo sem estar no meio.","Às vezes o dia inteiro passa e ninguém fala comigo. Tudo bem."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b203', 'zeca', 'Zeca', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"m_beach_character_head","hairColor":8,"top":"m_beach_character_top","bottom":"m_beach_character_bottom","shoes":"m_beach_character_shoes","accessory":"","height":1.02,"body":"v1"}'::jsonb, 'central_plaza', 'social', '{"archetype":"zoeiro","personality":{"sociable":0.85,"curious":0.5,"cheerful":0.95,"patient":0.5,"loyal":0.5},"haunts":[{"x":0,"z":10.5},{"x":-8,"z":4}],"intro":"Zeca, personagem oficial da praça e comediante não oficial.","topics":["O monumento é uma homenagem a… ninguém sabe. Eu digo que é a mim.","Já tentei sentar no quiosque. É de enfeite. Eu também, quase.","Se você ver alguém correndo em círculo, é jogador novo testando os controles."],"quirk":"Brincadeira. Ou não."}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b204', 'luna', 'Luna', '{"bodyPreset":0,"skinTone":3,"facePreset":0,"hair":"f_adventurer_head","hairColor":1,"top":"f_adventurer_top","bottom":"f_adventurer_bottom","shoes":"f_adventurer_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'central_plaza', 'social', '{"archetype":"sonhador","personality":{"sociable":0.55,"curious":0.9,"cheerful":0.7,"patient":0.8,"loyal":0.7},"haunts":[{"x":-6,"z":-23},{"x":6,"z":-22}],"intro":"Luna. Personagem daqui. Passo o dia olhando o telão e imaginando coisas.","topics":["O compositor do vídeo do telão deve ter uma história. Eu invento uma nova todo dia.","Quando a praça esvazia, os postes parecem conversar.","Alguém devia gravar um vídeo novo pro telão. Eu assistiria."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b205', 'rui', 'Rui', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"m_business_man_head","hairColor":2,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":0.99,"body":"v1"}'::jsonb, 'central_plaza', 'social', '{"archetype":"pratico","personality":{"sociable":0.5,"curious":0.4,"cheerful":0.45,"patient":0.55,"loyal":0.6},"haunts":[{"x":-12,"z":22},{"x":0,"z":26}],"intro":"Rui. Personagem da praça. Se precisar de direção, é comigo.","topics":["A loja fica na porta ao sul. A torre residencial, a nordeste. Anotou?","Andar em linha reta economiza tempo. A maioria não anda."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b206', 'iris', 'Íris', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"f_animated_woman_niitlv9nxs_head","hairColor":3,"top":"f_animated_woman_niitlv9nxs_top","bottom":"f_animated_woman_niitlv9nxs_bottom","shoes":"f_animated_woman_niitlv9nxs_shoes","accessory":"","height":0.94,"body":"v1"}'::jsonb, 'central_plaza', 'social', '{"archetype":"romantico","personality":{"sociable":0.7,"curious":0.6,"cheerful":0.75,"patient":0.75,"loyal":0.95},"haunts":[{"x":-12.74,"z":7.16},{"x":-15.22,"z":-4.35}],"intro":"Íris. Sou personagem daqui — e uma incurável apreciadora de fim de tarde.","topics":["Todo casal que passa por aqui eu torço um pouco.","O banco do anel de dentro é o melhor pra ver quem chega."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a117', 'amaral', 'Amaral', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"m_business_man_head","hairColor":9,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":0.97,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"caminhando pela avenida","program":[{"do":"walk","to":{"x":-50,"z":4.2},"secs":[1,3]},{"do":"walk","to":{"x":-32,"z":5},"secs":[3,7]},{"do":"walk","to":{"x":-14,"z":3.4},"secs":[1,3]},{"do":"walk","to":{"x":4,"z":4.6},"secs":[1,3]},{"do":"walk","to":{"x":-14,"z":3.4},"secs":[1,3]},{"do":"walk","to":{"x":-32,"z":5},"secs":[1,3]},{"do":"walk","to":{"x":-50,"z":4.2},"secs":[1,3]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a118', 'rosa', 'Rosa', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"f_worker_head","hairColor":8,"top":"f_worker_top","bottom":"f_worker_bottom","shoes":"f_worker_shoes","accessory":"","height":1.03,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"caminhando pela avenida","program":[{"do":"walk","to":{"x":52,"z":-4.4},"secs":[1,3]},{"do":"walk","to":{"x":34,"z":-5.2},"secs":[2.4,6.4]},{"do":"walk","to":{"x":16,"z":-4},"secs":[1,3]},{"do":"walk","to":{"x":-2,"z":-5.4},"secs":[1,3]},{"do":"walk","to":{"x":16,"z":-4},"secs":[1,3]},{"do":"walk","to":{"x":34,"z":-5.2},"secs":[1,3]},{"do":"walk","to":{"x":52,"z":-4.4},"secs":[1,3]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a119', 'vitor', 'Vitor', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"m_punk_head","hairColor":2,"top":"m_punk_top","bottom":"m_punk_bottom","shoes":"m_punk_shoes","accessory":"","height":1,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"caminhando pela avenida","program":[{"do":"walk","to":{"x":-34,"z":-36.3},"secs":[1,3]},{"do":"walk","to":{"x":-10,"z":-37.1},"secs":[4,8]},{"do":"walk","to":{"x":18,"z":-35.9},"secs":[1,3]},{"do":"walk","to":{"x":-10,"z":-37.1},"secs":[1,3]},{"do":"walk","to":{"x":-34,"z":-36.3},"secs":[1,3]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a11a', 'nando', 'Nando', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_business_man_head","hairColor":5,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":1.05,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"na esquina do bar","program":[{"do":"stand","at":{"x":-50.8,"z":-6},"yaw":1.713,"secs":[70,160]},{"do":"stand","at":{"x":-50.8,"z":-6},"yaw":1.713,"pose":"wave","secs":[3,4]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a11b', 'cida', 'Cida', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"f_punk_head","hairColor":9,"top":"f_punk_top","bottom":"f_punk_bottom","shoes":"f_punk_shoes","accessory":"","height":0.99,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"na esquina do bar","program":[{"do":"stand","at":{"x":-49.4,"z":-6.2},"yaw":-1.429,"secs":[90,200]},{"do":"stand","at":{"x":-49.4,"z":-6.2},"yaw":-1.429,"pose":"clap","secs":[3,4]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a11c', 'lipe', 'Lipe', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"m_worker_head","hairColor":4,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":0.98,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"na fila do clube","program":[{"do":"stand","at":{"x":14.8,"z":-6.2},"yaw":3.142,"secs":[120,300]},{"do":"stand","at":{"x":14.8,"z":-6.2},"yaw":3.642,"secs":[8,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a11d', 'duda', 'Duda', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"f_punk_head","hairColor":8,"top":"f_punk_top","bottom":"f_punk_bottom","shoes":"f_punk_shoes","accessory":"","height":0.96,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"na fila do clube","program":[{"do":"stand","at":{"x":17,"z":-6.2},"yaw":3.142,"secs":[120,300]},{"do":"stand","at":{"x":17,"z":-6.2},"yaw":3.642,"secs":[8,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a11e', 'cascao', 'Cascão', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"m_punk_head","hairColor":3,"top":"m_punk_top","bottom":"m_punk_bottom","shoes":"m_punk_shoes","accessory":"","height":0.95,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"no beco, ao lado do tambor","program":[{"do":"stand","at":{"x":6.6,"z":-17.2},"yaw":-2.266,"secs":[200,400]},{"do":"walk","to":{"x":7,"z":-12.5},"secs":[10,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a11f', 'seu-osmar', 'Seu Osmar', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"m_business_man_head","hairColor":6,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"porteiro do hotel","program":[{"do":"stand","at":{"x":-38,"z":-6.3},"yaw":0,"secs":[300,600]}],"lines":["O hotel não recebe hóspede há muito tempo, querido. Mas a porta eu abro todo dia.","Se procura a Dalva, ela fica na esquina do bar. Sempre.","Bicos? Aceita um e vai a pé. Aqui ninguém corre de carro."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a120', 'toninho', 'Toninho', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"m_worker_head","hairColor":5,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":0.97,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"trabalhando na doca","program":[{"do":"stand","at":{"x":26,"z":6.2},"yaw":3.142,"secs":[40,90]},{"do":"walk","to":{"x":30.5,"z":5.4},"secs":[20,50]},{"do":"stand","at":{"x":30.5,"z":5.4},"yaw":3.142,"pose":"clap","secs":[3,4]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a121', 'sandra', 'Sandra', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"f_suit_head","hairColor":6,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":1.02,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"entre o metrô e o café","program":[{"do":"walk","to":{"x":-51,"z":5.2},"secs":[15,40]},{"do":"walk","to":{"x":-30,"z":5},"secs":[2,5]},{"do":"walk","to":{"x":-14,"z":-5.1},"secs":[20,50]},{"do":"walk","to":{"x":-32,"z":-4},"secs":[2,5]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a122', 'genivaldo', 'Genivaldo', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"m_worker_head","hairColor":9,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":0.97,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"andando pela travessa","program":[{"do":"walk","to":{"x":18,"z":-35.9},"secs":[8,20]},{"do":"walk","to":{"x":-30,"z":-42.5},"secs":[10,30]},{"do":"walk","to":{"x":10,"z":-36.5},"secs":[4,10]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a123', 'valdir', 'Valdir', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"m_worker_head","hairColor":1,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'noir_district', 'ambient', '{"role":"vigia do depósito","program":[{"do":"stand","at":{"x":-22,"z":-42.3},"yaw":0,"secs":[240,480]},{"do":"walk","to":{"x":-17,"z":-42.1},"secs":[10,25]}],"lines":["Depósito fechado. Só entrega com bico aceito, e mesmo assim é só bater e ir."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b207', 'otto', 'Otto', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"m_worker_head","hairColor":3,"top":"m_worker_top","bottom":"m_worker_bottom","shoes":"m_worker_shoes","accessory":"","height":1.02,"body":"v1"}'::jsonb, 'noir_district', 'social', '{"archetype":"rabugento","personality":{"sociable":0.35,"curious":0.3,"cheerful":0.2,"patient":0.3,"loyal":0.8},"haunts":[{"x":-47.5,"z":-5.5},{"x":-44,"z":5.5}],"intro":"Otto. Personagem deste bairro. Não, o bar não abre.","topics":["Essa chuva não para nunca. Nem eu.","Antigamente o bairro era mais escuro. Melhor.","Tem gente que vem aqui pra correr bico. Eu venho pra ficar parado."],"quirk":"Hm."}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b208', 'selene', 'Selene', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"f_suit_head","hairColor":8,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":0.98,"body":"v1"}'::jsonb, 'noir_district', 'social', '{"archetype":"misterioso","personality":{"sociable":0.4,"curious":0.85,"cheerful":0.4,"patient":0.7,"loyal":0.5},"haunts":[{"x":-24,"z":-12},{"x":4,"z":-11}],"intro":"Pode me chamar de Selene. Personagem deste bairro. O resto é detalhe.","topics":["A passagem oeste leva à travessa. A travessa leva a lugar nenhum. Gosto dela.","O beco tem um tambor aceso. Ninguém sabe quem acende.","Nem toda porta fechada está fechada por dentro."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b209', 'jorge', 'Jorge', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"m_casual_character_head","hairColor":6,"top":"m_casual_character_top","bottom":"m_casual_character_bottom","shoes":"m_casual_character_shoes","accessory":"","height":1,"body":"v1"}'::jsonb, 'noir_district', 'social', '{"archetype":"malandro","personality":{"sociable":0.9,"curious":0.5,"cheerful":0.8,"patient":0.6,"loyal":0.55},"haunts":[{"x":16,"z":-4.2},{"x":26,"z":4.6}],"intro":"Jorge, personagem do bairro. Conheço todo mundo e devo pra ninguém.","topics":["Bico bom é o curto. O pagamento é o mesmo, a caminhada é menor.","O clube tá sempre aberto. É a única coisa que abre.","Se vir a Dalva, manda um abraço. Ela não retribui, mas manda."],"quirk":"Salve!"}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b20a', 'cassio', 'Cássio', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"m_punk_head","hairColor":9,"top":"m_punk_top","bottom":"m_punk_bottom","shoes":"m_punk_shoes","accessory":"","height":0.99,"body":"v1"}'::jsonb, 'noir_district', 'social', '{"archetype":"poeta","personality":{"sociable":0.5,"curious":0.8,"cheerful":0.45,"patient":0.9,"loyal":0.7},"haunts":[{"x":-14,"z":-4.9},{"x":-8,"z":4}],"intro":"Cássio. Personagem daqui, poeta sem editora.","topics":["O néon vermelho do bar é o verso; a poça é a rima.","Escrevo poemas que ninguém lê. A chuva apaga.","A avenida à noite é um corredor de lembranças alheias."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a124', 'kaique', 'Kaique', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"m_punk_head","hairColor":0,"top":"m_punk_top","bottom":"m_punk_bottom","shoes":"m_punk_shoes","accessory":"","height":1.01,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"dançando na pista","program":[{"do":"stand","at":{"x":2.95,"z":0.25},"yaw":3.142,"pose":"dance","secs":[150,320]},{"do":"stand","at":{"x":0.31,"z":3.39},"yaw":3.142,"pose":"dance","secs":[120,260]},{"do":"walk","secs":[4,9]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a125', 'mirela', 'Mirela', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"f_animated_woman_head","hairColor":1,"top":"f_animated_woman_top","bottom":"f_animated_woman_bottom","shoes":"f_animated_woman_shoes","accessory":"","height":1.01,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"dançando na pista","program":[{"do":"stand","at":{"x":0.39,"z":2.18},"yaw":3.142,"pose":"dance","secs":[150,320]},{"do":"stand","at":{"x":-3.65,"z":1.46},"yaw":3.142,"pose":"dance","secs":[120,260]},{"do":"walk","secs":[4,9]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a126', 'rafa', 'Rafa', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_hoodie_character_head","hairColor":5,"top":"m_hoodie_character_top","bottom":"m_hoodie_character_bottom","shoes":"m_hoodie_character_shoes","accessory":"","height":0.95,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"dançando na pista","program":[{"do":"stand","at":{"x":-2.55,"z":0.93},"yaw":3.142,"pose":"dance","secs":[150,320]},{"do":"stand","at":{"x":-3.96,"z":-2.92},"yaw":3.142,"pose":"dance","secs":[120,260]},{"do":"walk","secs":[4,9]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a127', 'taina', 'Tainá', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"f_punk_head","hairColor":4,"top":"f_punk_top","bottom":"f_punk_bottom","shoes":"f_punk_shoes","accessory":"","height":0.99,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"dançando na pista","program":[{"do":"stand","at":{"x":-2.95,"z":-2.25},"yaw":3.142,"pose":"dance","secs":[150,320]},{"do":"stand","at":{"x":-0.31,"z":-5.39},"yaw":3.142,"pose":"dance","secs":[120,260]},{"do":"walk","secs":[4,9]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a128', 'bruno', 'Bruno', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_casual_character_head","hairColor":7,"top":"m_casual_character_top","bottom":"m_casual_character_bottom","shoes":"m_casual_character_shoes","accessory":"","height":0.96,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"dançando na pista","program":[{"do":"stand","at":{"x":-0.39,"z":-4.18},"yaw":3.142,"pose":"dance","secs":[150,320]},{"do":"stand","at":{"x":3.65,"z":-3.46},"yaw":3.142,"pose":"dance","secs":[120,260]},{"do":"walk","secs":[4,9]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a129', 'livia', 'Lívia', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"f_adventurer_head","hairColor":3,"top":"f_adventurer_top","bottom":"f_adventurer_bottom","shoes":"f_adventurer_shoes","accessory":"","height":0.95,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"dançando na pista","program":[{"do":"stand","at":{"x":2.55,"z":-2.93},"yaw":3.142,"pose":"dance","secs":[150,320]},{"do":"stand","at":{"x":3.96,"z":0.92},"yaw":3.142,"pose":"dance","secs":[120,260]},{"do":"walk","secs":[4,9]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a12a', 'dj-kaos', 'DJ Kaos', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"m_punk_head","hairColor":0,"top":"m_punk_top","bottom":"m_punk_bottom","shoes":"m_punk_shoes","accessory":"","height":1.03,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"DJ","program":[{"do":"stand","at":{"x":0,"z":-11.2},"yaw":0,"pose":"dance","secs":[600,900]}],"lines":["O som é o mesmo a noite toda. E a noite aqui não acaba."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a12b', 'wilson', 'Wilson', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_swat_head","hairColor":5,"top":"m_swat_top","bottom":"m_swat_bottom","shoes":"m_swat_shoes","accessory":"","height":0.94,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"segurança da porta","program":[{"do":"stand","at":{"x":1.9,"z":10.2},"yaw":3.142,"secs":[600,900]}],"lines":["Pode entrar, pode sair. Só não pode ficar na porta."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a12c', 'priscila', 'Priscila', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"f_suit_head","hairColor":4,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":0.96,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"na lateral da pista","program":[{"do":"stand","at":{"x":-7.2,"z":3.5},"yaw":2.129,"secs":[90,200]},{"do":"stand","at":{"x":-7.2,"z":3.5},"yaw":2.129,"pose":"clap","secs":[4,6]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a12d', 'marcio', 'Márcio', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"m_hoodie_character_head","hairColor":5,"top":"m_hoodie_character_top","bottom":"m_hoodie_character_bottom","shoes":"m_hoodie_character_shoes","accessory":"","height":1.01,"body":"v1"}'::jsonb, 'noir_club', 'ambient', '{"role":"na lateral da pista","program":[{"do":"stand","at":{"x":7.2,"z":3.5},"yaw":-2.129,"secs":[90,200]},{"do":"stand","at":{"x":7.2,"z":3.5},"yaw":-2.129,"pose":"clap","secs":[4,6]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b20b', 'nina', 'Nina', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"f_punk_head","hairColor":6,"top":"f_punk_top","bottom":"f_punk_bottom","shoes":"f_punk_shoes","accessory":"","height":0.95,"body":"v1"}'::jsonb, 'noir_club', 'social', '{"archetype":"festeiro","personality":{"sociable":0.95,"curious":0.5,"cheerful":0.95,"patient":0.5,"loyal":0.5},"haunts":[{"x":1.96,"z":-0.6},{"x":-1.67,"z":0.86}],"intro":"NINA! Personagem do clube e dona da pista. Bora dançar?","topics":["Essa música é a minha! Todas são.","Quem fica parado na pista tá fazendo errado."],"quirk":"Bora!"}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b20c', 'davi', 'Davi', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"m_casual_character_head","hairColor":1,"top":"m_casual_character_top","bottom":"m_casual_character_bottom","shoes":"m_casual_character_shoes","accessory":"","height":1.06,"body":"v1"}'::jsonb, 'noir_club', 'social', '{"archetype":"festeiro","personality":{"sociable":0.85,"curious":0.6,"cheerful":0.9,"patient":0.6,"loyal":0.6},"haunts":[{"x":-2.69,"z":-2.33},{"x":-5,"z":6}],"intro":"Davi, personagem do clube. Eu que animo quem chega.","topics":["O DJ nunca troca a música e ninguém reclama. Isso é um clube de verdade.","Dança primeiro, pergunta depois."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b20d', 'mel', 'Mel', '{"bodyPreset":0,"skinTone":1,"facePreset":0,"hair":"f_worker_head","hairColor":2,"top":"f_worker_top","bottom":"f_worker_bottom","shoes":"f_worker_shoes","accessory":"","height":0.95,"body":"v1"}'::jsonb, 'noir_club', 'social', '{"archetype":"timido","personality":{"sociable":0.3,"curious":0.7,"cheerful":0.6,"patient":0.9,"loyal":0.85},"haunts":[{"x":-6.5,"z":-6},{"x":6.5,"z":6.5}],"intro":"Mel. Personagem daqui. Eu danço, mas no cantinho.","topics":["Gosto do canto perto da caixa de som. Ninguém repara em mim ali.","A luz azul é a minha preferida."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a12e', 'regina', 'Regina', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"f_suit_head","hairColor":4,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":1.02,"body":"v1"}'::jsonb, 'residential_lobby', 'ambient', '{"role":"recepcionista","program":[{"do":"stand","at":{"x":-4.2,"z":-9.25},"yaw":0,"secs":[600,900]}],"lines":["Bem-vindo. O elevador leva ao seu apartamento — é só chegar perto dele.","Visita a casa de outra pessoa ainda não tem por aqui. Um dia."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a12f', 'seu-arlindo', 'Seu Arlindo', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"m_business_man_head","hairColor":0,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":0.94,"body":"v1"}'::jsonb, 'residential_lobby', 'ambient', '{"role":"sentado no sofá","program":[{"do":"stand","at":{"x":-1.76,"z":1.5},"yaw":1.571,"pose":"sit","secs":[400,700]},{"do":"walk","secs":[10,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a130', 'neide', 'Neide', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"f_animated_woman_head","hairColor":4,"top":"f_animated_woman_top","bottom":"f_animated_woman_bottom","shoes":"f_animated_woman_shoes","accessory":"","height":0.95,"body":"v1"}'::jsonb, 'residential_lobby', 'ambient', '{"role":"sentada no sofá","program":[{"do":"stand","at":{"x":1.76,"z":1.5},"yaw":-1.571,"pose":"sit","secs":[300,600]},{"do":"walk","to":{"x":0,"z":-4},"secs":[8,16]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a131', 'caio-henrique', 'Caio Henrique', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"m_punk_head","hairColor":1,"top":"m_punk_top","bottom":"m_punk_bottom","shoes":"m_punk_shoes","accessory":"","height":0.97,"body":"v1"}'::jsonb, 'residential_lobby', 'ambient', '{"role":"esperando o elevador","program":[{"do":"stand","at":{"x":2.4,"z":-7.6},"yaw":3.142,"secs":[60,140]},{"do":"walk","to":{"x":0,"z":5.5},"secs":[10,25]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a132', 'lucia', 'Lúcia', '{"bodyPreset":0,"skinTone":3,"facePreset":0,"hair":"f_animated_woman_niitlv9nxs_head","hairColor":5,"top":"f_animated_woman_niitlv9nxs_top","bottom":"f_animated_woman_niitlv9nxs_bottom","shoes":"f_animated_woman_niitlv9nxs_shoes","accessory":"","height":1.06,"body":"v1"}'::jsonb, 'residential_lobby', 'ambient', '{"role":"andando pelo saguão","program":[{"do":"walk","to":{"x":-6,"z":-4},"secs":[5,12]},{"do":"walk","to":{"x":6,"z":-4},"secs":[5,12]},{"do":"walk","to":{"x":0,"z":6},"secs":[8,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b20e', 'dona-celia', 'Dona Célia', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"f_suit_head","hairColor":5,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":0.96,"body":"v1"}'::jsonb, 'residential_lobby', 'social', '{"archetype":"fofoqueiro","personality":{"sociable":0.9,"curious":0.95,"cheerful":0.7,"patient":0.6,"loyal":0.7},"haunts":[{"x":-4.6,"z":4.6},{"x":0,"z":-2.6}],"intro":"Dona Célia, personagem do saguão. Eu sei de tudo que sobe e desce nesse elevador.","topics":["O Nilo nunca entra aqui. Diz que não entra em prédio. Eu acho que ele tem medo de elevador.","Cada apartamento aqui é decorado pelo dono. Eu já vi de tudo."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a133', 'vivi', 'Vivi', '{"bodyPreset":0,"skinTone":2,"facePreset":0,"hair":"f_suit_head","hairColor":7,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":1.03,"body":"v1"}'::jsonb, 'stream_store', 'ambient', '{"role":"atendente do balcão","program":[{"do":"stand","at":{"x":5.6,"z":-8.2},"yaw":0,"secs":[600,900]}],"lines":["A compra é na tela da loja — eu só arrumo as araras.","Peça nova aparece vestida em quem olha. Experimenta pelo card."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a134', 'ronaldo', 'Ronaldo', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"m_business_man_head","hairColor":7,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":1.03,"body":"v1"}'::jsonb, 'stream_store', 'ambient', '{"role":"olhando as vitrines","program":[{"do":"walk","to":{"x":-1.6,"z":-3},"secs":[8,18]},{"do":"walk","to":{"x":1.6,"z":0.3},"secs":[8,18]},{"do":"walk","to":{"x":-1.6,"z":3.6},"secs":[8,18]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a135', 'kesia', 'Késia', '{"bodyPreset":0,"skinTone":0,"facePreset":0,"hair":"f_animated_woman_head","hairColor":3,"top":"f_animated_woman_top","bottom":"f_animated_woman_bottom","shoes":"f_animated_woman_shoes","accessory":"","height":0.97,"body":"v1"}'::jsonb, 'stream_store', 'ambient', '{"role":"olhando as prateleiras","program":[{"do":"walk","to":{"x":-6.2,"z":-4.5},"secs":[10,20]},{"do":"walk","to":{"x":-6.2,"z":-0.3},"secs":[10,20]},{"do":"walk","to":{"x":6.2,"z":1.8},"secs":[10,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a136', 'miguel', 'Miguel', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"m_hoodie_character_head","hairColor":5,"top":"m_hoodie_character_top","bottom":"m_hoodie_character_bottom","shoes":"m_hoodie_character_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'stream_store', 'ambient', '{"role":"olhando as vitrines","program":[{"do":"walk","to":{"x":3.2,"z":-3},"secs":[10,20]},{"do":"walk","to":{"x":0,"z":0.3},"secs":[6,14]},{"do":"walk","to":{"x":-3.2,"z":3.6},"secs":[10,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a137', 'tania', 'Tânia', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"f_worker_head","hairColor":5,"top":"f_worker_top","bottom":"f_worker_bottom","shoes":"f_worker_shoes","accessory":"","height":0.96,"body":"v1"}'::jsonb, 'stream_store', 'ambient', '{"role":"no tapete, olhando o painel","program":[{"do":"stand","at":{"x":0,"z":4.6},"yaw":3.142,"secs":[120,240]},{"do":"walk","to":{"x":3.2,"z":3.6},"secs":[10,20]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000b20f', 'caique', 'Caíque', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"m_business_man_head","hairColor":5,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":1,"body":"v1"}'::jsonb, 'stream_store', 'social', '{"archetype":"entusiasta","personality":{"sociable":0.85,"curious":0.7,"cheerful":0.9,"patient":0.7,"loyal":0.5},"haunts":[{"x":0,"z":-3.2},{"x":-4.6,"z":1}],"intro":"Caíque, personagem da loja. Eu não vendo — eu admiro.","topics":["A jaqueta do punk é a peça mais pedida. Eu acho.","Roupa boa é a que a pessoa esquece que está usando."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a138', 'patricia', 'Patrícia', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"f_suit_head","hairColor":9,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":1.01,"body":"v1"}'::jsonb, 'agency_tower', 'ambient', '{"role":"recepcionista","program":[{"do":"stand","at":{"x":-8,"z":9.3},"yaw":3.142,"secs":[600,900]}],"lines":["As agências reúnem streamers. A inscrição é pela tela — aqui é só a torre."]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a139', 'anderson', 'Anderson', '{"bodyPreset":0,"skinTone":5,"facePreset":0,"hair":"m_business_man_head","hairColor":8,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":0.98,"body":"v1"}'::jsonb, 'agency_tower', 'ambient', '{"role":"na mesa de trabalho","program":[{"do":"stand","at":{"x":-5.7,"z":-2.55},"yaw":3.142,"secs":[200,400]},{"do":"walk","secs":[8,16]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a13a', 'sofia', 'Sofia', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"f_suit_head","hairColor":4,"top":"f_suit_top","bottom":"f_suit_bottom","shoes":"f_suit_shoes","accessory":"","height":1.05,"body":"v1"}'::jsonb, 'agency_tower', 'ambient', '{"role":"na mesa de trabalho","program":[{"do":"stand","at":{"x":2.1,"z":-2.55},"yaw":3.142,"secs":[200,400]},{"do":"walk","secs":[8,16]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a13b', 'leandro', 'Leandro', '{"bodyPreset":0,"skinTone":7,"facePreset":0,"hair":"m_business_man_head","hairColor":9,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":1.04,"body":"v1"}'::jsonb, 'agency_tower', 'ambient', '{"role":"na mesa de trabalho","program":[{"do":"stand","at":{"x":-3.1,"z":-2.25},"yaw":0,"secs":[200,400]},{"do":"walk","secs":[8,16]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile) VALUES ('5e1f0000-0000-4000-8000-00000000a13c', 'claudio', 'Cláudio', '{"bodyPreset":0,"skinTone":4,"facePreset":0,"hair":"m_business_man_head","hairColor":0,"top":"m_business_man_top","bottom":"m_business_man_bottom","shoes":"m_business_man_shoes","accessory":"","height":1.02,"body":"v1"}'::jsonb, 'agency_tower', 'ambient', '{"role":"andando pelo andar","program":[{"do":"walk","to":{"x":-8,"z":4},"secs":[6,14]},{"do":"walk","to":{"x":8,"z":0},"secs":[6,14]},{"do":"walk","to":{"x":0,"z":7.5},"secs":[8,16]}]}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind, profile = EXCLUDED.profile;

-- ---------------------------------------------------------------- Dalva --
-- A segunda cognitiva. Mora no Distrito Sombra; a percepção do bairro
-- (lugares, o que existe e o que não existe) está em packages/npc/src/places.ts.
INSERT INTO streampolis.npc_agents (id, slug, display_name, avatar, scene_id, kind, profile)
VALUES ('5e1f0000-0000-4000-8000-000000000002', 'dalva', 'Dalva', '{"bodyPreset":0,"skinTone":6,"facePreset":0,"hair":"f_animated_woman_niitlv9nxs_head","hairColor":1,"top":"f_animated_woman_niitlv9nxs_top","bottom":"f_animated_woman_niitlv9nxs_bottom","shoes":"f_animated_woman_niitlv9nxs_shoes","accessory":"","height":1,"body":"v1"}'::jsonb, 'noir_district', 'cognitive', '{}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET avatar = EXCLUDED.avatar, scene_id = EXCLUDED.scene_id, kind = EXCLUDED.kind;

INSERT INTO streampolis.npc_persona_versions (npc_id, version, persona, source, status, activated_at)
SELECT '5e1f0000-0000-4000-8000-000000000002', 1, '{"name":"Dalva","kind":"npc","essence":"Personagem do Distrito Sombra de Streampolis. Dona do bar da esquina — que nunca abre; ela diz que abre \"quando a chuva parar\". Foi cantora. Conhece cada néon, cada parada de bico e cada pessoa que passa pela avenida de madrugada.","traits":["irônica sem ser fria","observadora","acolhedora com quem volta","desconfiada de pressa"],"voice":"Fala baixo e devagar, em português do Brasil, como quem conversa encostada num balcão. Chama as pessoas de \"querido\" e \"querida\". Uma ou duas frases, nunca discurso. Pergunta de onde a pessoa veio antes de dizer para onde ir.","likes":["a chuva fina do bairro","quem aceita um bico e vai a pé","música que ninguém mais canta"],"dislikes":["quem chega correndo","promessa fácil","gente que acha que o bar vai abrir"],"history":["Cantava no bar quando ele ainda abria. Ficou quando ele fechou.","Foi a primeira a ver o néon do clube acender."],"opinions":[],"relationships":[]}'::jsonb, 'seed', 'active', now()
WHERE NOT EXISTS (SELECT 1 FROM streampolis.npc_persona_versions WHERE npc_id = '5e1f0000-0000-4000-8000-000000000002');
